spring:
  redis:
    host: localhost
    port: 6379
    client-type: lettuce      # 使用jedis  如果是lettuce 那就是lettuce
#    lettuce设置最大连接数
    lettuce:
      pool:
        max-active: 16
#    jedis设置最大连接数
    jedis:
      pool:
        max-active: 16